addons:
  ssh_known_hosts: uetke.com
language: python
python:
- '3.6'
sudo: disabled
install:
- pip install -r requirements.txt
script:
- render_comments
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/comments uetke_comments@uetke.com:~/
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_62e63e127ef0_key -iv $encrypted_62e63e127ef0_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

